[Hackney] POC fetching of completion photos
mysociety/open311-adapter pull request #155
Opened 2020-10-14 12:48 UTC by struan

This will fetch any photos that were added as part of an update with a
status of in_progress or fixed.

2020-10-26 15:35 UTC, davea requested changes
Sorry to be pernickety, and I know it doesn't affect the code changes in this PR, but the `geometry` property has been removed from Alloy so we shouldn't include it in our fixtures anymore.

2020-10-26 15:35 UTC, davea commented on t/open311/endpoint/json/alloyv2/inspect_search_photo.json
> +      "geometry":{
We should use the `attributes_itemsGeometry` attribute instead of the `geometry` property from now on, to mirror the Alloy API.

2020-10-27 15:30 UTC, davea approved these changes
📸  🚦  ✅

2022-01-25 12:00 UTC, LouiseMySociety commented
Agreed to close and will reopen if customer asked for it again.

2022-01-25 12:00 UTC, closed without merging