[Bexley] Handle private comments field
mysociety/open311-adapter pull request #156
Opened 2020-10-19 12:43 UTC by chrismytton

This is to work with the changes at the FixMyStreet end to send private comments over when they are entered on the report form.

The FixMyStreet bits are in https://github.com/mysociety/fixmystreet/pull/3222

Not sure if this is the best approach. Couple of questions:

- Is this the best way to add the private comments to the description field?
- Is it OK to add the private_comments attribute to all UK Councils like this?

2020-10-21 14:50 UTC, davea approved these changes
🔒 🔍 🗒️

2020-11-20 09:12 UTC, dracos commented on perllib/Open311/Endpoint/Integration/UK/Bexley.pm
> +    my $private_comments = $report->{attributes}{private_comments};
This doesn't work once it tries to submit to Confirm as the attribute is still present and Confirm rejects it as "private_comments is not a valid attribute type code".
I think this would remove the attribute along with fetching it:
```suggestion
    my $private_comments = delete $report->{attributes}{private_comments};
```

2020-11-20 09:15 UTC, dracos requested changes
Needs a fix from testing of Confirm submission (assume might apply to others as well, this should fix for all assuming this var isn't needed after this point)

2020-11-20 10:39 UTC, chrismytton commented on perllib/Open311/Endpoint/Integration/UK/Bexley.pm
> +    my $private_comments = $report->{attributes}{private_comments};
Thanks, have fixed in e7626f1.

2020-11-20 11:03 UTC, dracos approved these changes

2020-12-23 10:41 UTC, chrismytton commented
I've changed `hidden_field` to `server_set`, which I think is what it should have been in the first place.

With `hidden_field` it was creating an extra `private_comments` field in the FMS HTML, which was then causing problems down the line meaning the private comments weren't actually coming through.

2021-02-08 14:47 UTC, chrismytton commented
@dracos I've tried adding tests for the Bexley private comments bug with Confirm (wasn't sending private comments to Confirm because Confirm uses the description from the attributes). However, I can't figure out how to get this properly wrapped up in a test.

I've added one approach in b190d29bf932a0dbd6b820286afa05f92d4cd5f9, but it's failing for reasons I can't quite understand. I also tried using the same approach as `t/open311/endpoint/bexley.t` with using mocks of the `Open311::Endpoint::Integration::UK::Bexley::*` classes, but got mired in errors around missing attributes because the services in that test are generated with the simple `new_service` method, so don't have the `private_comments` attribute.

What am I missing? Is there something else I need to mock to get this approach to work?

2021-02-08 16:42 UTC, dracos commented
You're creating a Bexley endpoint, passing in a Bexley::ConfirmTrees config file (which a Multi subclass doesn't do anything with, so is ignored). So when it comes to look up the service in Bexley (first thing it does, as part of validating the received input), tries to pass it to its children, doesn't find anything, hence the error returned.
Looks like `t/open311/endpoint/confirm_upload.t` creates dummy Multi and a Confirm child in order to override this, as it says there bit fiddly, but can't think of an easier way off-hand, you could create a dummy child of Bexley and do the same. Or come up with a way to override a Bexley subclass config from within.

2021-02-09 10:31 UTC, chrismytton commented
@dracos Thanks! The `t/open311/endpoint/confirm_upload.t` example was enough for me to build on and get it all working 🎉

2021-02-10 08:41 UTC, dracos approved these changes
🔒

2021-03-23 09:15 UTC, merged