[Echo] Take first value found rather than last
mysociety/open311-adapter pull request #177
Opened 2021-03-31 09:54 UTC by dracos

For https://github.com/mysociety/fixmystreet/pull/3348
Also includes the parent change from another branch so it's hopefully easier to merge that in later.

2021-03-31 12:48 UTC, struan approved these changes
👍

2021-04-16 13:09 UTC, struan requested changes
one variable name tweak and a bit more testing.

2021-04-16 13:09 UTC, struan commented on perllib/Open311/Endpoint/Integration/Echo.pm
> +        my $extra = 0;
might be clearer if this was called `$extra_count`

2021-04-16 13:09 UTC, struan commented on t/open311/endpoint/echo.t
> +                is $child[1]->value, 12;
should this not also check there's a second event here with a reason of 7?

2021-04-16 13:22 UTC, dracos commented on t/open311/endpoint/echo.t
> +                is $child[1]->value, 12;
It did that above when it runs the same test as the non-multi request, then this is extra to test the second one on top.

2021-04-16 13:43 UTC, struan commented on t/open311/endpoint/echo.t
> +                is $child[1]->value, 12;
ah yes, so it does.

2021-04-16 13:54 UTC, merged