[Central Beds] Send report title to enquiry Location field in Symology
mysociety/open311-adapter pull request #181
Opened 2021-04-12 20:36 UTC by davea

For https://github.com/mysociety/fixmystreet-commercial/issues/2231

2021-04-13 06:39 UTC, dracos requested changes
One change not needed, I think, is all

2021-04-13 06:39 UTC, dracos commented on perllib/Open311/Endpoint/Integration/Symology.pm
> +    foreach (qw/fixmystreet_id easting northing UnitID RegionSite NSGRef contributed_by report_url description/) {
I don't think this line change is needed - neither of the new variables are used/needed in the $request objject (a "Description" value is used, so the lowercase version might be confusing).

The $args->{report_url} check a few lines down could presumably start using $args->{attributes}->{report_url} instead now that it could be present.

2021-04-13 08:22 UTC, davea commented on perllib/Open311/Endpoint/Integration/Symology.pm
> +    foreach (qw/fixmystreet_id easting northing UnitID RegionSite NSGRef contributed_by report_url description/) {
You're right that they're not used in $request, but left alone they get appended to the `Description` by the loop on L163. Maybe the better thing to do would be to remove them in `CentralBedfordshire::process_service_request_args`, given they're specific to that integration.

2021-04-13 08:24 UTC, dracos commented on perllib/Open311/Endpoint/Integration/Symology.pm
> +    foreach (qw/fixmystreet_id easting northing UnitID RegionSite NSGRef contributed_by report_url description/) {
Oh yes! Yes, I guess so, easy to move back if it becomes more generic at some point.

2021-04-16 11:03 UTC, dracos approved these changes

2021-05-10 12:39 UTC, merged