[Bexley] use Symology Event Type as external status
mysociety/open311-adapter pull request #182
Opened 2021-04-15 10:52 UTC by struan

Use the Event Type column as the external status code if present in the
update CSV.

Fixes mysociety/fixmystreet-commercial#2279

2021-04-21 16:33 UTC, davea requested changes
One warning to squash is all.

2021-04-21 16:33 UTC, davea commented on perllib/Open311/Endpoint/Integration/UK/Bexley/Symology.pm
> +    return undef unless $status eq 'not_councils_responsibility';
`$status` may be `undef` here which causes an uninitialized value warning, how about:

```suggestion
    return undef unless $status && $status eq 'not_councils_responsibility';
```

2021-04-22 15:54 UTC, davea approved these changes
LGTM!

2021-07-02 13:08 UTC, struan commented
Extra mapping of categories added

2021-07-05 10:02 UTC, chrismytton approved these changes
🟢

2021-07-29 15:30 UTC, merged