[Bexley] Add next action to updates
mysociety/open311-adapter pull request #223
Opened 2022-07-22 08:34 UTC by MorayMySoc

https://github.com/mysociety/societyworks/issues/3059

* Adds check for nsg_ref parameter and, if it exists, look up relevant code and add it to the Next Action

2022-07-22 11:50 UTC, davea reviewed
Looking good so far

2022-08-01 13:29 UTC, davea requested changes
One small change is all!

2022-08-01 13:29 UTC, davea commented on perllib/Open311/Endpoint/Role/mySociety.pm
> +            nsg_ref => '//str',
Rather than adding a new top-level attribute I think it would be better/cleaner to follow the same pattern as for Oxfordshire just below on L180 and use `attribute[nsg_ref]`.

2022-08-01 19:19 UTC, davea approved these changes
👍

2022-08-12 15:55 UTC, MorayMySoc commented
Sorry - issue with the jurisdiction_id which my test cheated into working, pointed out by @dracos after tried on staging and didn't work.

2022-08-15 08:29 UTC, davea approved these changes
Oops, sorry for missing that. Looks good!

2022-09-14 08:43 UTC, merged