Set different comment on uploads if bulky collection
mysociety/open311-adapter pull request #249
Opened 2023-01-31 19:58 UTC by nephila-nacrea

Peterborough want bulky goods collection photos to be marked with the comment 'Bulky waste photo' (see https://3.basecamp.com/4020879/buckets/26662378/todos/5608057275).

2023-02-01 13:32 UTC, davea requested changes
Looks like a nice simple change, but please chuck a test in :)

2023-02-02 13:59 UTC, davea commented on perllib/Open311/Endpoint/Integration/Bartec.pm
> +        $args->{service_name} = $service->service_name;
We already have the category name here so seemed easier to use that rather than whatever Bartec returns (plus it makes the test easier as the XML doesn't include that value!)

2023-02-02 13:59 UTC, davea commented
@nephila-nacrea I've added a test, hopefully that looks OK.

2023-02-06 17:21 UTC, nephila-nacrea commented
> @nephila-nacrea I've added a test, hopefully that looks OK.

Thank you; that looks good to me - would you be able to approve the PR?

2023-02-07 12:28 UTC, davea approved these changes

2023-02-15 19:42 UTC, merged