[Camden] Send photo URLs to field in Symology
mysociety/open311-adapter pull request #253
Opened 2023-02-13 17:01 UTC by chrismytton

This field has been configured to accept FixMyStreet photo URLs and display them in the Symology interface.

Fixes https://github.com/mysociety/societyworks/issues/3492

2023-02-16 14:07 UTC, dracos requested changes
Just little bit of documentation would be good :) Looks fine, can we chase Central Beds to get the same code there up and running, do we know what was happening there?

2023-02-17 09:56 UTC, chrismytton commented on perllib/Open311/Endpoint/Integration/UK/Camden.pm
> +sub process_service_request_args {
Added in 0588add

2023-02-17 09:58 UTC, chrismytton commented
> can we chase Central Beds to get the same code there up and running, do we know what was happening there

Looks like Dave never got a response from his question last summer: https://mysocietysupport.freshdesk.com/a/tickets/1076

But yes, probably worth re-visiting the Central Beds code once this has been confirmed to work.

2023-02-17 10:19 UTC, dracos approved these changes

2023-02-17 10:39 UTC, chrismytton commented
This is on the staging site now.

2023-02-21 17:42 UTC, MorayMySoc commented
There is an update in what is being looked for - I'm not 100% this is the full solution as not sure if the 'attr' would need to change. Though potential global impact https://3.basecamp.com/4020879/buckets/27695641/todos/5740705094#__recording_5862342384

2023-02-22 15:55 UTC, merged