[Symology] Script to cleanup remote XML files
mysociety/open311-adapter pull request #259
Opened 2023-03-07 17:27 UTC by chrismytton

Looks for XML files that are older than one week on Symology's SFTP server and removes them.

It gets the files timestamp from the filename, rather than relying on the creation time of the remote file.

2023-03-08 12:17 UTC, dracos requested changes
Password change suggestion is all, looks good :)

2023-03-08 16:02 UTC, chrismytton commented on bin/symology/cleanup_remote_files
> +    done < <(sshpass -p "$OPTION_updates_sftp__password" sftp -q "$OPTION_updates_sftp__username@$OPTION_updates_sftp__host" << EOF
Done in https://github.com/mysociety/open311-adapter/pull/259/commits/1b59c38db998eee5c1143e68fef98d10c3d1dda1

2023-03-08 16:02 UTC, chrismytton commented
I've also added some documentation at the top of the script.

2023-03-09 09:21 UTC, chrismytton commented
Did a slight tweak to the documentation to properly list the yaml bits we're using. Change for docs now in 59cb44d9105bde8228e1408b3f947d14d82df1de.

2023-03-09 10:17 UTC, dracos approved these changes
Looks good, thanks :)

2023-03-09 12:16 UTC, merged