Adding a report for Abavus integration
mysociety/open311-adapter pull request #277
Opened 2023-05-25 11:47 UTC by MorayMySoc

This is the integration set up to send a report to Abavus according to the specification.

Still to be added is the updating a status from a report already created.

2023-05-26 11:20 UTC, dracos requested changes
Looking good, some suggestions :)

2023-05-26 11:20 UTC, dracos commented on t/open311/endpoint/abavus.t
> +my @services = $bucks_endpoint->services;
Is fine, would probably group these test in a few subtests (e.g. 'services', 'posting report'), just for scanning through

2023-05-26 11:20 UTC, dracos commented on t/open311/endpoint/abavus.t
> +sub api_call {
This mocking works fine, but does mean none of the api_call code is being tested (e.g. setting the auth header might be worth checking). Could you have the same checking, but at a lower level, perhaps done as a mock of LWP::UserAgent's `request` maybe?

2023-05-26 11:20 UTC, dracos commented on perllib/Open311/Endpoint/Integration/Abavus.pm
> +        return {} if $ENV{TEST_MODE};
As you're mocking this in the test, do you need these guards, here and below?

2023-05-26 11:20 UTC, dracos commented on t/open311/endpoint/abavus.yml
> +{
I'd have this either as YAML, or valid JSON :)

2023-05-26 11:20 UTC, dracos commented on perllib/Open311/Endpoint/Integration/Abavus.pm
> +            my $data = $self->service_extra_data->{$code};
extra_code looks good, I wonder if extra_data could be tweaked slightly to make it easier. I'd change type to datatype (and value 'dropdown' to 'singlevaluelist') and change choices to values, and I'd make it a list rather than a hash, because question order might be important (presumably sorting won't always be correct). So I'd have:

```
  "service_extra_data": {
      DISPLAY_ISSUE_17821_C: [
        {
         code: "DISPLAY_ISSUE_TYPE_646538_I",
          description: "Incorrect or broken",
          required: 1,
          datatype: 'singlevaluelist',
          values: {
            DISPLAY_916276_A: Incorrect,
            DISPLAY_916277_A: Broken
          }
        },
        {
          code: "DISPLAY_CONTACT_646539_I",
          description: "May we contact you?",
          type: 'text',
          required: 0,
        }
      },
...
```
And then you can loop over and use each hash directly as %params, no need to map anything across, it's already what you want.

2023-05-30 13:01 UTC, davea approved these changes
Looks good! One debugging line to remove, but 👍

2023-05-30 16:39 UTC, merged