[Alloy] Cache reconstruct calls.
mysociety/open311-adapter pull request #290
Opened 2023-07-18 16:33 UTC by dracos

2023-07-18 20:19 UTC, davea requested changes
There's a crash in there, not sure how the tests didn't pick it up though.

2023-07-18 20:19 UTC, davea commented on perllib/Open311/Endpoint/Integration/AlloyV2.pm
> +            return decode_json($file->slurp_raw);
This returns something different to L1315, think it needs to be this otherwise it'll crash:

```suggestion
            return decode_json($file->slurp_raw)->{item};
```

(Alternatively guess we could save a few bytes on disk by changing L1312 to just store `$resource->{item}`)

2023-07-19 12:55 UTC, dracos commented on perllib/Open311/Endpoint/Integration/AlloyV2.pm
> +            return decode_json($file->slurp_raw);
Test never calls the same thing twice, hence why it didn't crash, thanks for spotting, will try and make it do so.

2023-07-19 12:56 UTC, dracos commented on perllib/Open311/Endpoint/Integration/AlloyV2.pm
> +            return decode_json($file->slurp_raw);
I think I do want to store the whole thing as it includes metadata that theoretically might be useful (though I guess could always be looked up).

2023-07-19 13:20 UTC, merged