Northumberland assigned to user
mysociety/open311-adapter pull request #315
Opened 2023-11-21 15:30 UTC by nephila-nacrea

2023-11-30 15:12 UTC, dracos requested changes
Looks good, all clear to read 👍  Couple of small suggestions to the block is all :)

2023-11-30 15:12 UTC, dracos commented on perllib/Open311/Endpoint/Integration/AlloyV2.pm
> +            my $assigned_to_user = {};
Don't think this line is needed, could be `my $assigned_to_user` inside the if.

2023-11-30 15:12 UTC, dracos commented on perllib/Open311/Endpoint/Integration/AlloyV2.pm
> +                $assigned_to_user
This block is fine, wondered if you'd like to rejig it to something like:

```
my $assigned_to_user = $assigned_to_users->{$assigned_to_user_id} ||= do {
    # There is a possibility the assigned-to user is not already
    # in the $assigned_to_users hash; do another lookup if so
    $self->get_assigned_to_users($resource)->{$assigned_to_user_id};
};
```
which then handles the checking/reassignment in a neater block.

2023-12-01 10:51 UTC, nephila-nacrea commented on perllib/Open311/Endpoint/Integration/AlloyV2.pm
> +                $assigned_to_user
Ooh nice and pithy, I wasn't that familiar with using do{} in this kind of way :-)

2023-12-01 13:57 UTC, dracos approved these changes
🧑‍🚀

2023-12-12 09:37 UTC, merged