[Echo] Strip suffixes defined by _
mysociety/open311-adapter pull request #348
Opened 2024-07-12 09:41 UTC by MorayMySoc

If we have used a suffix in the categories of FMS to allow us to use one Event Type with separate category names, we strip the suffix before sending to Echo so the report is sent to the base Event type

https://github.com/mysociety/societyworks/issues/4365

2024-07-12 09:42 UTC, MorayMySoc commented
I don't think Symology or ATAK should be affected as you said - couldn't see how if so.

2024-07-12 11:03 UTC, dracos requested changes

2024-07-12 11:03 UTC, dracos commented on perllib/Integrations/Echo.pm
> +    my ($event_type) = split /_/, $args->{event_type};
I think this is happening too late in the process? We'd want to be able to e.g. use the actual event type ID in `_get_data_value` for attribute lookups, not the 'duplicate' one.

`process_service_request_args` when you first get the service_code coming in would be better, I think.

2024-07-15 09:23 UTC, dracos approved these changes

2024-07-15 11:42 UTC, merged